spring:
  application:
    name: server
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true

server:
  port: 8090

# For local testing
POSTGRES_URL: jdbc:postgresql://localhost:5432/prerev_tinder_db
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
